#ifndef LEDCONTROLLER_LED_MODES_H
#define LEDCONTROLLER_LED_MODES_H

#define MODE_OFF 0x00
#define MODE_SIMPLE 0x01
#define MODE_RAINBOW 0x02
#define MODE_FILLING 0x03
#define MODE_MARQUEE 0x04
#define MODE_ROTATING 0x05
#define MODE_SWEEP 0x06
#define MODE_APB 0x07
#define MODE_HALVES 0x08
#define MODE_DOUBLE_FILL 0x09
#define MODE_HIGHS 0x0A
#define MODE_SOURCES 0x0B
#define MODE_PIECES 0x0C
#define MODE_EMPTY1 0x0D
#define MODE_EMPTY2 0x0E
#define MODE_DEMO 0x0F

#define MODE_CSGO 0x10
#define MODE_MUSIC 0x20
#define MODE_TEMP 0x30

#endif //LEDCONTROLLER_LED_MODES_H